"""empty message

Revision ID: 04a340be61b5
Revises: 6bf7f1f3de8a
Create Date: 2023-09-06 18:14:58.922369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04a340be61b5"
down_revision = "6bf7f1f3de8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=True))
        batch_op.create_unique_constraint("email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("email", type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
